name: ramclustr-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base >=4.1
  - r-rlang >=1.1.0
  - r-devtools
  - r-biocmanager
  - r-dynamictreecut
  - r-fastcluster
  - r-gplots
  - r-ggplot2
  - bioconductor-msnbase
  - bioconductor-xcms
  - r-curl
  - r-webchem
  - r-stringi
  - r-jsonlite
  - r-stringr
  - r-xml2
  - r-e1071
  - r-interpretmsspectrum <=1.3.3
  - r-languageserver
  - r-testthat
  - r-readxl
  - radian
  - r-rmarkdown
  - qpdf
  - r-rhub
  - r-rentrez
  - r-covr
  - r-patrick
  - r-httr
  - bioconductor-preprocesscore